"use client";

import './globals.css'
import type { Metadata } from 'next'
import { RecoilRoot } from 'recoil'
import { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gamebuddy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <RecoilRoot>
      <html lang="en">
        <body className={inter.className}>{children}</body>
        <div><Toaster position='top-center' /></div>
      </html>
    </RecoilRoot>
  )
}
